### ISSUE TITLE
can't download this generator

### ISSUE THREAD

**Issue by iurii77** [OnionIoT/oledQrCodeGenerator#1]
> fatal: unable to access 'https://github.com/OnionIoT/oledQrCodeGenerator.git/': Error reading ca cert file /etc/ssl/certs
> /ca-certificates.crt - mbedTLS: (-0x3E00) PK - Read/write of file failed 

How can I fix it?
Thanks

**Comment by greenbreakfast** [comment]
Is this on the Omega? Try following this: http://docs.onion.io/omega2-docs/installing-and-using-git.html

**Comment by adamgweeks** [comment]
Sorry to ask the question here, but in theory would this also work with an RPI?

Would it also work with a 128 x 128 display by simply editing main.py?
